### ISSUE TITLE
Customizable register form

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1149]
Need to be able to customise some things per app.
New url will be: /customers/signup/{app_id} (also /customers/signin)

Need to be able to change:
- Logo in top left corner
- Background image
- Color scheme

Just allow uploading a custom 'theme' css string for an app. If there is no custom theme present, load the default (our city app logo's/colours).

**Comment by lucasvanhalst** [comment]
Threefold style css:
```css
#main_container {
    background-size: cover;
    background: #0c2e73 url(https://threefold.io/img/tf-bg.jpg) no-repeat 100% 0;
    min-height: 100vh;
}

#header{
    background-color: #0D2E75;
}

#logo{
    background: url(https://threefold.io/svg/threefold-logo-white.svg) no-repeat;
    background-size: cover;
    width: 160px;
}

.btn-wizard {
    background: #0A3073;
    color: white;
}

.btn-wizard:hover, .btn-wizard:focus, .btn-wizard:active {
    background: #3A69B9;
    color: white;
}

.white-box {
    border: 1px solid #0C2E73;
}
```

(also, upload the pictures to gcs instead of using urls from the website)
